import { useEffect, useState } from "react";
import { useLocation } from "react-router-dom";
import { ScanSearch, Cpu, Activity, ShieldCheck, Play, LoaderCircle, AlertTriangle } from "lucide-react";
import PageShell from "../components/PageShell";
import { useInteractions } from "../context/InteractionContext";
import { inferInterests, type InterestAnalysis } from "../lib/interestInference";
import { engagementScore, skipPenalty } from "../lib/recommendations";

export default function AIAnalysis() {
  const { reels } = useInteractions();
  const location = useLocation();
  const [analysis, setAnalysis] = useState<InterestAnalysis | null>(null);
  const [running, setRunning] = useState(false);
  const avg = (values: number[]) => Math.round(values.reduce((a, b) => a + b, 0) / values.length);
  const signals = [{ label: "Watch depth", value: avg(reels.map((r) => r.watchPercentage)), color: "bg-accent-400" }, { label: "Engagement score", value: avg(reels.map(engagementScore)), color: "bg-signal-400" }, { label: "Save ratio", value: Math.round(reels.filter((r) => r.saved).length / reels.length * 100), color: "bg-lime-400" }, { label: "Skip penalty", value: avg(reels.map(skipPenalty)), color: "bg-amber-400" }];
  const singleReel = [...reels].sort((a, b) => engagementScore(b) - engagementScore(a))[0];
  const oneReelAnalysis = singleReel ? inferInterests([singleReel]) : null;
  const run = () => { setRunning(true); window.setTimeout(() => { setAnalysis(inferInterests(reels)); setRunning(false); }, 550); };
  useEffect(() => { if (location.state?.runDemo) run(); }, []);
  return <PageShell eyebrow="Judge Mode" title="AI Analysis" description="The model weighs engagement, learning value, skips and related concepts to infer the interests behind your feed." icon={<ScanSearch className="h-3.5 w-3.5" />}>
    <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><span className="text-xs text-slate-500">Ready to evaluate {reels.length} current reel interactions</span><button onClick={run} disabled={running} className="btn-primary disabled:cursor-wait disabled:opacity-70">{running ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Play className="h-4 w-4 fill-ink-950" />}{running ? "Analyzing signals…" : "Analyze interests"}</button></div>
    <div className="grid grid-cols-1 gap-4 lg:grid-cols-3"><div className="card animate-fade-up p-5 lg:col-span-2"><div className="flex items-center gap-2"><Activity className="h-4 w-4 text-accent-300" /><h3 className="text-sm font-semibold text-slate-200">Engagement Signals</h3></div><div className="mt-5 space-y-4">{signals.map((s) => <div key={s.label}><div className="flex items-center justify-between text-xs"><span className="text-slate-400">{s.label}</span><span className="font-mono text-slate-300">{s.value}%</span></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-white/5"><div className={`h-full rounded-full ${s.color}`} style={{ width: `${s.value}%` }} /></div></div>)}</div></div><div className="card animate-fade-up p-5" style={{ animationDelay: "0.1s" }}><div className="flex items-center gap-2"><Cpu className="h-4 w-4 text-lime-400" /><h3 className="text-sm font-semibold text-slate-200">Model Status</h3></div><div className="mt-4 space-y-3 text-sm"><Row k="Model" v="concept-graph-v1" /><Row k="Records" v={`${reels.length} reels`} /><Row k="State" v={running ? "Processing" : analysis ? "Current" : "Ready"} />{analysis && <Row k="Confidence" v={`${analysis.confidence}%`} />}</div><div className="mt-4 flex items-center gap-2 rounded-lg border border-lime-400/20 bg-lime-400/5 p-2.5 text-xs text-lime-300"><ShieldCheck className="h-4 w-4" /> Analysis stays in this browser</div></div></div>
    {analysis && <section className="animate-fade-up mt-4 grid grid-cols-1 gap-4 lg:grid-cols-3"><div className="card p-5 lg:col-span-2"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Primary interest</p><h2 className="mt-2 font-display text-3xl font-bold text-accent-200">{analysis.primaryInterest}</h2><div className="mt-4 flex flex-wrap gap-2">{analysis.secondaryInterests.map((interest) => <span key={interest} className="chip border-white/10 bg-white/[0.03] text-slate-300">{interest}</span>)}</div><div className="mt-5 space-y-2">{analysis.evidence.map((item) => <p key={item} className="text-sm leading-relaxed text-slate-400">{item}</p>)}</div></div><div className="card p-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Confidence</p><p className="mt-2 font-display text-4xl font-bold text-lime-400">{analysis.confidence}%</p><p className="mt-1 text-sm text-slate-300">{analysis.confidenceLevel} evidence consistency</p><div className="mt-5 space-y-2">{Object.entries(analysis.interestScores).slice(0, 4).map(([interest, score]) => <div key={interest} className="text-xs"><div className="flex justify-between text-slate-400"><span>{interest}</span><span>{score}</span></div><div className="mt-1 h-1.5 rounded-full bg-white/5"><div className="h-full rounded-full bg-accent-400" style={{ width: `${score}%` }} /></div></div>)}</div></div><div className="card p-5 lg:col-span-3"><div className="flex items-center gap-2 text-amber-300"><AlertTriangle className="h-4 w-4" /><h3 className="text-sm font-semibold">Counterfactual: what if?</h3></div><p className="mt-3 text-sm text-slate-400">With only <span className="text-slate-200">{singleReel?.title}</span>: {oneReelAnalysis?.confidence ?? 0}% confidence. With the full {reels.length}-reel history: <span className="text-lime-300">{analysis.confidence}%</span> confidence.</p><div className="mt-4 border-t border-white/5 pt-4"><h3 className="text-sm font-semibold text-slate-200">Negative signals</h3><div className="mt-2 space-y-2">{analysis.negativeSignals.map((item) => <p key={item} className="text-sm text-slate-400">{item}</p>)}</div></div></div></section>}
  </PageShell>;
}
function Row({ k, v }: { k: string; v: string }) { return <div className="flex items-center justify-between"><span className="text-slate-500">{k}</span><span className="font-mono text-slate-200">{v}</span></div>; }
