import { Sparkles, ArrowUpRight, BrainCircuit } from "lucide-react";
import PageShell from "../components/PageShell";
import { useInteractions } from "../context/InteractionContext";
import { inferInterests } from "../lib/interestInference";
import { getNextSkills, getRecommendations } from "../lib/recommendationEngine";
import { getReelConcepts } from "../lib/interestInference";
import { qualityGuard } from "../lib/qualityGuard";

export default function Recommendations() {
  const { reels } = useInteractions();
  const analysis = inferInterests(reels);
  const recommendations = getRecommendations(reels, analysis);
  const filtered = qualityGuard(reels).filter((decision) => decision.filtered);
  const nextSkills = getNextSkills(analysis, reels);
  const lead = recommendations[0];
  return <PageShell eyebrow="For You" title="Recommendations" description="Ranked from your live concept profile, with repeated topics and hype content deliberately demoted." icon={<Sparkles className="h-3.5 w-3.5" />}>
    {lead && <section className="animate-fade-up mb-5 card overflow-hidden"><div className="border-b border-accent-400/15 bg-accent-400/[0.04] px-5 py-3"><span className="chip border-accent-400/20 bg-accent-400/10 text-accent-200">Agent Decision · Live</span></div><div className="grid grid-cols-1 gap-x-8 gap-y-4 p-5 sm:grid-cols-2"><Decision label="Current Reel" value={lead.currentReel?.title ?? "No interaction available"} /><Decision label="Interest Detected" value={lead.interestDetected} accent /><Decision label="Why" value={analysis.evidence[0]} wide /><Decision label="Recommended Tech Reel" value={lead.recommendedReel.title} accent /><Decision label="Category" value={lead.recommendedReel.topics[0] ?? lead.category} /><Decision label="Why This Recommendation" value={lead.whyRecommendation} wide /><Decision label="Difficulty" value={lead.difficulty} /><Decision label="Confidence" value={`${analysis.confidenceLevel} · ${lead.confidence}%`} /></div></section>}
    {lead && <section className="animate-fade-up card relative overflow-hidden p-5 sm:p-6"><div className="pointer-events-none absolute -right-16 -top-16 h-48 w-48 rounded-full bg-accent-400/10 blur-3xl" /><div className="relative flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><BrainCircuit className="h-4 w-4 text-accent-300" /><span className="chip border-accent-400/20 bg-accent-400/10 text-accent-200">Top recommendation</span></div><h2 className="mt-4 font-display text-2xl font-bold text-white">{lead.recommendedReel.title}</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-slate-400">{lead.whyRecommendation}</p><div className="mt-4 flex flex-wrap gap-2"><span className="chip border-white/10 bg-white/[0.03] text-slate-300">{lead.interestDetected}</span><span className="chip border-white/10 bg-white/[0.03] text-slate-300">{lead.difficulty}</span><span className="chip border-white/10 bg-white/[0.03] text-slate-300">{lead.recommendedReel.topics[0]}</span></div></div><div className="shrink-0 text-left sm:text-right"><p className="font-mono text-4xl font-bold text-lime-400">{lead.matchScore}%</p><p className="text-[10px] uppercase tracking-wider text-slate-500">match score</p><p className="mt-2 text-xs text-slate-400">{lead.confidence}% profile confidence</p></div></div><Breakdown recommendation={lead} /></section>}
    <section className="mt-5 grid grid-cols-1 gap-4 lg:grid-cols-2"><div className="card p-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Interest evolution</p><p className="mt-3 text-sm text-slate-300">{lead?.currentReel?.title ?? "Observed reels"} <span className="text-accent-300">→</span> {lead?.currentReel ? getReelConcepts(lead.currentReel).join(", ") : "Concepts"} <span className="text-accent-300">→</span> {analysis.primaryInterest} <span className="text-accent-300">→</span> {lead?.recommendedReel.topics[0] ?? "Technology"}</p><p className="mt-3 text-xs text-slate-500">Naive: one Java signal → another Java reel. Our system aggregates related concepts and intentionally favors useful adjacent learning.</p></div><div className="card p-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Next skills</p><div className="mt-3 flex flex-wrap gap-2">{nextSkills.map((skill) => <span key={skill} className="chip border-lime-400/20 bg-lime-400/5 text-lime-300">{skill}</span>)}</div><p className="mt-3 text-xs text-slate-500">Adjacent skills adapt to the current primary interest.</p></div></section>
    <section className="mt-4 card p-5"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-amber-300">Filtered by Quality Guard</p><div className="mt-3 space-y-2">{filtered.slice(0, 3).map((item) => <p key={item.reel.id} className="text-sm text-slate-400"><span className="font-medium text-slate-200">{item.reel.title}</span> — {item.reasons.join(", ")}. Not eligible for the primary recommendation.</p>)}{!filtered.length && <p className="text-sm text-slate-400">No current clips meet the low-quality filter threshold.</p>}</div></section>
    <section className="mt-5"><div className="mb-3 flex items-center gap-2 px-1"><h2 className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Next best</h2><div className="h-px flex-1 bg-gradient-to-r from-white/10 to-transparent" /></div><div className="space-y-3">{recommendations.slice(1, 5).map((recommendation, index) => <div key={recommendation.recommendedReel.id} className="animate-fade-up card group flex items-center gap-4 p-4 transition-all hover:border-white/20 hover:bg-ink-800/80" style={{ animationDelay: `${0.05 * index}s` }}><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-white/10 bg-white/[0.03] font-mono text-sm text-slate-400">{String(index + 2).padStart(2, "0")}</span><div className="min-w-0 flex-1"><span className="chip border-accent-400/20 bg-accent-400/10 text-accent-200">{recommendation.recommendedReel.topics[0]}</span><p className="mt-1.5 truncate text-sm font-semibold text-slate-100">{recommendation.recommendedReel.title}</p><p className="mt-1 truncate text-xs text-slate-500">{recommendation.whyRecommendation}</p></div><div className="hidden text-right sm:block"><p className="font-mono text-lg font-semibold text-lime-400">{recommendation.matchScore}%</p><p className="text-[10px] uppercase tracking-wider text-slate-600">match</p></div><ArrowUpRight className="h-5 w-5 shrink-0 text-slate-600 transition-all group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-accent-300" /></div>)}</div></section>
  </PageShell>;
}
function Breakdown({ recommendation }: { recommendation: ReturnType<typeof getRecommendations>[number] }) { const values = [["Interest", recommendation.breakdown.interestMatch], ["Signal", recommendation.breakdown.interactionSignal], ["Learning", recommendation.breakdown.educationalValue], ["Novelty", recommendation.breakdown.novelty], ["Hype risk", recommendation.breakdown.hypeRisk]]; return <div className="relative mt-5 grid grid-cols-2 gap-3 border-t border-white/5 pt-4 sm:grid-cols-5">{values.map(([label, value]) => <div key={label as string}><p className="text-[10px] uppercase tracking-wider text-slate-600">{label}</p><p className="mt-1 font-mono text-sm text-slate-300">{value as number}%</p></div>)}</div>; }
function Decision({ label, value, accent, wide }: { label: string; value: string; accent?: boolean; wide?: boolean }) { return <div className={wide ? "sm:col-span-2" : ""}><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-slate-500">{label}</p><p className={`mt-1 text-sm leading-relaxed ${accent ? "font-semibold text-accent-200" : "text-slate-300"}`}>{value}</p></div>; }
